shorten ci for debugging purposes

diff --git a/.github/workflows/process.yml b/.github/workflows/process.yml
--- a/.github/workflows/process.yml
+++ b/.github/workflows/process.yml
@@ -17,46 +17,46 @@ env:
   python-version: '3.10'
 
 jobs:
-  unit-test:
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest]
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
-      - name: Setup python and hatch
-        uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
-      - name: Run unit tests with coverage report
-        run: |
-          hatch run test:tests-cov tests/unit
-      - name: Upload coverage to Codecov
-        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
-        env:
-          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-        with:
-          fail_ci_if_error: ${{ github.ref_name == 'main' }}
+  # unit-test:
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-latest, macos-latest]
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
+  #     - name: Setup python and hatch
+  #       uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
+  #     - name: Run unit tests with coverage report
+  #       run: |
+  #         hatch run test:tests-cov tests/unit
+  #     - name: Upload coverage to Codecov
+  #       uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
+  #       env:
+  #         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+  #       with:
+  #         fail_ci_if_error: ${{ github.ref_name == 'main' }}
 
-  integration-test:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
-      - name: Setup python and hatch
-        uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
-        with:
-          python-version: ${{ env.python-version }}
-      - name: Run integration tests
-        run: hatch run test.py${{ env.python-version }}:tests-integration
+  # integration-test:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
+  #     - name: Setup python and hatch
+  #       uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
+  #       with:
+  #         python-version: ${{ env.python-version }}
+  #     - name: Run integration tests
+  #       run: hatch run test.py${{ env.python-version }}:tests-integration
 
-  example-test:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
-      - name: Setup python and hatch
-        uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
-        with:
-          python-version: ${{ env.python-version }}
-      - name: Run example tests
-        run: hatch run test.py${{ env.python-version }}:tests-examples
+  # example-test:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
+  #     - name: Setup python and hatch
+  #       uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
+  #       with:
+  #         python-version: ${{ env.python-version }}
+  #     - name: Run example tests
+  #       run: hatch run test.py${{ env.python-version }}:tests-examples
 
   regression-test:
     runs-on: ubuntu-latest
@@ -105,55 +105,55 @@ jobs:
           name: sig-tfs
           path: tracking/*.json
 
-  pre-commit-quality-check:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
-      - name: Setup python and hatch
-        uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
-        with:
-          python-version: ${{ env.python-version }}
-      - name: Run Hatch linting tasks
-        uses: Fusion-Power-Plant-Framework/fppf-actions/hatch-lint@c6af22fc8d00be67cca53a61177301462f499fb2
+  # pre-commit-quality-check:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
+  #     - name: Setup python and hatch
+  #       uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
+  #       with:
+  #         python-version: ${{ env.python-version }}
+  #     - name: Run Hatch linting tasks
+  #       uses: Fusion-Power-Plant-Framework/fppf-actions/hatch-lint@c6af22fc8d00be67cca53a61177301462f499fb2
 
-  improve_quality_check:
-    runs-on: ubuntu-latest
-    if: github.event_name == 'pull_request'
-    needs: [pre-commit-quality-check]
-    steps:
-      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
-        with:
-          fetch-depth: 0
-      - name: Setup python and hatch
-        uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
-        with:
-          python-version: ${{ env.python-version }}
+  # improve_quality_check:
+  #   runs-on: ubuntu-latest
+  #   if: github.event_name == 'pull_request'
+  #   needs: [pre-commit-quality-check]
+  #   steps:
+  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup python and hatch
+  #       uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
+  #       with:
+  #         python-version: ${{ env.python-version }}
 
-      - name: Get changed files
-        id: changes
-        shell: bash
-        run: |
-          set -euo pipefail
+  #     - name: Get changed files
+  #       id: changes
+  #       shell: bash
+  #       run: |
+  #         set -euo pipefail
 
-          git diff --name-only origin/${{ github.base_ref }} \
-            | grep -E '\.pyi?$' \
-            > changed_files.txt || true
+  #         git diff --name-only origin/${{ github.base_ref }} \
+  #           | grep -E '\.pyi?$' \
+  #           > changed_files.txt || true
 
-          {
-            echo "files<<EOF"
-            cat changed_files.txt
-            echo "EOF"
-          } >> "$GITHUB_OUTPUT"
+  #         {
+  #           echo "files<<EOF"
+  #           cat changed_files.txt
+  #           echo "EOF"
+  #         } >> "$GITHUB_OUTPUT"
 
-      - name: Run improvement lint
-        if: steps.changes.outputs.files != ''
-        shell: bash
-        run: |
-          set -euo pipefail
+  #     - name: Run improvement lint
+  #       if: steps.changes.outputs.files != ''
+  #       shell: bash
+  #       run: |
+  #         set -euo pipefail
 
-          mapfile -t files <<< "${{ steps.changes.outputs.files }}"
+  #         mapfile -t files <<< "${{ steps.changes.outputs.files }}"
 
-          hatch run lint:fmt_extra "${files[@]}"
+  #         hatch run lint:fmt_extra "${files[@]}"
 
 
   tracking:
@@ -208,48 +208,48 @@ jobs:
           git commit -m "${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
           git push
 
-  docs:
-    concurrency:
-      group: docs-jobs
-      cancel-in-progress: false
-    runs-on: ubuntu-latest
-    # depends on tracking; only runs upon merge to main
-    needs: tracking
-    if: github.ref == 'refs/heads/main'
-    steps:
-      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
-        with:
-          fetch-depth: 0
-      - name: Setup python and hatch
-        uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
-        with:
-          python-version: ${{ env.python-version }}
-      - run: git config --global --add safe.directory '*'
-      - name: Download STF_TF.json files
-        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
-        with:
-          name: sig-tfs
-          path: tracking/
-      - name: Download MFILEs
-        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
-        with:
-          name: tracked-mfiles
-          path: tracking/
-      - run: mv tracking/large_tokamak_nof.SIG_TF.json tracking/large_tokamak_nof_SIG_TF.json
-      - name: Create an example plot summary
-        run: hatch run process plot summary -f tracking/large_tokamak_nof_MFILE.DAT
-      - name: Move plot summary file to docs images
-        run: mv tracking/large_tokamak_nof_MFILE.DATSUMMARY.pdf documentation/source/images/plot_summary.pdf
-      - run: hatch run docs:build
-      - name: Download tracking html
-        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
-        with:
-          name: tracking-html
-      - run: mv tracking.html site || cp site/404.html site/tracking.html
-      - name: Upload documentation page
-        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
-        with:
-          path: site/
-      - name: Deploy GitHub pages
-        id: deployment
-        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
+  # docs:
+  #   concurrency:
+  #     group: docs-jobs
+  #     cancel-in-progress: false
+  #   runs-on: ubuntu-latest
+  #   # depends on tracking; only runs upon merge to main
+  #   needs: tracking
+  #   if: github.ref == 'refs/heads/main'
+  #   steps:
+  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup python and hatch
+  #       uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2
+  #       with:
+  #         python-version: ${{ env.python-version }}
+  #     - run: git config --global --add safe.directory '*'
+  #     - name: Download STF_TF.json files
+  #       uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
+  #       with:
+  #         name: sig-tfs
+  #         path: tracking/
+  #     - name: Download MFILEs
+  #       uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
+  #       with:
+  #         name: tracked-mfiles
+  #         path: tracking/
+  #     - run: mv tracking/large_tokamak_nof.SIG_TF.json tracking/large_tokamak_nof_SIG_TF.json
+  #     - name: Create an example plot summary
+  #       run: hatch run process plot summary -f tracking/large_tokamak_nof_MFILE.DAT
+  #     - name: Move plot summary file to docs images
+  #       run: mv tracking/large_tokamak_nof_MFILE.DATSUMMARY.pdf documentation/source/images/plot_summary.pdf
+  #     - run: hatch run docs:build
+  #     - name: Download tracking html
+  #       uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
+  #       with:
+  #         name: tracking-html
+  #     - run: mv tracking.html site || cp site/404.html site/tracking.html
+  #     - name: Upload documentation page
+  #       uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
+  #       with:
+  #         path: site/
+  #     - name: Deploy GitHub pages
+  #       id: deployment
+  #       uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
